site_name: Daniel Test Docs
pages:
    - Home: index.md
    - About: _test_wiki/1.md
theme: readthedocs
docs/
    index.md
    _test_wiki/1.md
    _test_wiki/2.md
    _test_wiki/3.md
    _test_wiki/4.md